<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\User::factory()->create();
        \App\Models\Company::factory()->create();
        DB::table('company_user')->insert([
            'company_id'=>1,
            'user_id'=>1
        ]);
        DB::table('roles')->insert([
            [
                'company_id'=>1,
                'name'=>'Super User',
                'permissions' => 'SU'
            ],
            [
                'company_id'=>1,
                'name'=>'Accounting',
                'permissions'=>'ADE,ADV,ADD,BSE,BSV,BSD,FYE,FYV,FYD,JGE,JGV,JGD,JTE,JTV,JTD,JE,JV,JD,PTCE,PTCV,PTCD,PTE,PTV,PTD,PTRCE,PTRCV,PTRCD'
            ]
        ]);
        DB::table('role_user')->insert([
            'role_id'=>1,
            'user_id'=>1
        ]);
        DB::table('stores')->insert([
            'company_id'=>1,
            'name'=>'Pretoria',
            'contact_person'=>'The boss',
            'mobile_number'=>'0821234567',
            'email'=>'boss@democompany.com',
            'is_active'=>1
        ]);
        DB::table('counters')->insert([
            [
                'company_id'=>1,
                'name'=>'document_flow',
                'prefix'=>NULL,
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'customers',
                'prefix'=>'C',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'suppliers',
                'prefix'=>'S',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'products',
                'prefix'=>NULL,
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'credit_note',
                'prefix'=>'CN',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'quotation',
                'prefix'=>'Q',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'receipts',
                'prefix'=>'R',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'sales_order',
                'prefix'=>'SO',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'tax_invoice',
                'prefix'=>'INV',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'goods_received_note',
                'prefix'=>'GRN',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'goods_delivery_note',
                'prefix'=>'GDN',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'purchase_order',
                'prefix'=>'PO',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'supplier_invoice',
                'prefix'=>'SI',
                'number'=>1
            ],
            [
                'company_id'=>1,
                'name'=>'transactions',
                'prefix'=>NULL,
                'number'=>1
            ],
        ]);
        DB::table('financial_years')->insert([
            'company_id'=>1,
            'name'=>'2021/2022',
            'start_date'=>'2021-03-01',
            'end_date'=>'2022-02-08',
            'is_active'=>1
        ]);
        DB::table('setup_accounting')->insert([
            'company_id'=>1,
            'trade_classification'=>43,
            'charge_delivery_cost'=>0,
            'default_credit_limit'=>0,
            'retained_earnings'=>'5200000',
            'profit_loss_year'=>'2800000',
            'exchange_variances_account'=>'4210000',
            'bank_charges'=>'3200000',
            'sales_account'=>'1000000',
            'sales_discount_account'=>'2700000',
            'purchase_discount_account'=>'2700000',
            'debtor_control_account'=>'8000000',
            'bad_debt_account'=>'3150000',
            'bad_debt_recovered_account'=>'2850000',
            'supplier_control_account'=>'9000000',
            'inventory_account'=>'7700000',
            'cogs_account'=>'2000000',
            'vat_control_account'=>'9500000',
            'vat_output'=>'9500100',
            'vat_input'=>'9500200',
            'inventory_adjustments_account'=>'7700000',
            'rounding_account'=>'9999000',
            'round_to_nearest'=>0,
            'depreciation_period'=>365,
            'tax_number'=>NULL,
            'is_vat_registered'=>0,
            'vat_number'=>null,
            'uif_number'=>null,
            'sdl_number'=>NULL,
            'paye_number'=>NULL,
            'import_number'=>NULL,
            'financial_year_id'=>1,
            'accounting_period_id'=>NULL,
            'quote_valid_days'=>30,
            'statement_message'=>NULL,
            'tax_invoice_message'=>NULL,
            'sales_order_message'=>NULL,
            'quotation_message'=>NULL,
            'receipt_message'=>NULL,
            'credit_note_message'=>NULL,
        ]);
    }
}
